add_newline = true

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[λ](bold blue)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[λ](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "on [$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = 'dimmed bold green'

[java]
disabled = true

[nodejs]
disabled = true

[terraform]
disabled = true

[git_metrics]
disabled = false